<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

*   Identify duplicate values in the dataset.

*   Remove duplicate values from the dataset.

*   Identify missing values in the dataset.

*   Impute the missing values in the dataset.

*   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [1]:
import pandas as pd

Load the dataset into a dataframe.

In [2]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

In [3]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11547,25136,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,36.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Difficult
11548,25137,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Poland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Tech...,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
11549,25138,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,34.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
11550,25141,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Switzerland,No,"Secondary school (e.g. American high school, G...",NaN,...,Somewhat less welcome now than last year,NaN,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
11551,25142,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,30.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Easy

## Finding duplicates

In this section you will identify duplicate values in the dataset.

Find how many duplicate rows exist in the dataframe.

In [4]:
# your code goes here
duplicated= df[df.duplicated('Respondent')]

In [5]:
duplicated
print("Number of duplicated rows are :",duplicated.shape[0])

Number of duplicated rows are : 154

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [6]:
# your code goes here
df.drop_duplicates(subset=['Respondent'],inplace=True)

Verify if duplicates were actually dropped.

In [10]:
# your code goes here
duplicate=df[df.duplicated()]
print("Number of duplicated rows are :",duplicate.shape[0])

Number of duplicated rows are : 0

In [11]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11547,25136,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,36.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Difficult
11548,25137,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Poland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Tech...,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
11549,25138,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,34.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
11550,25141,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Switzerland,No,"Secondary school (e.g. American high school, G...",NaN,...,Somewhat less welcome now than last year,NaN,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
11551,25142,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,30.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Easy

In [26]:
df[["CompFreq","CompTotal"]].head(20)

   CompFreq  CompTotal
0    Yearly    61000.0
1    Yearly   138000.0
2    Yearly    90000.0
3   Monthly    29000.0
4    Yearly    90000.0
5   Monthly     9500.0
6   Monthly     3000.0
7    Yearly   103000.0
8    Yearly    69000.0
9   Monthly     8000.0
10  Monthly     7000.0
11   Yearly   114000.0
12   Weekly     2000.0
13   Weekly    22000.0
14  Monthly    96000.0
15   Yearly   156000.0
16   Yearly    18000.0
17  Monthly     6400.0
18  Monthly     5000.0
19   Yearly   400000.0

## Finding Missing values

Find the missing values for all columns.

In [12]:
pd.set_option("display.max_rows",100)
df.isnull().sum()

Respondent                   0
MainBranch                   0
Hobbyist                     0
OpenSourcer                  0
OpenSource                  81
Employment                   0
Country                      0
Student                     51
EdLevel                    112
UndergradMajor             737
EduOther                   164
OrgSize                     96
DevType                     65
YearsCode                    9
Age1stCode                  13
YearsCodePro                16
CareerSat                    0
JobSat                       1
MgrIdiot                   493
MgrMoney                   497
MgrWant                    493
JobSeek                      0
LastHireDate                 0
LastInt                    413
FizzBuzz                    37
JobFactors                   3
ResumeUpdate                39
CurrencySymbol               0
CurrencyDesc                 0
CompTotal                  809
CompFreq                   206
ConvertedComp              816
WorkWeekHrs                122
WorkPlan                   121
WorkChallenge              164
WorkRemote                   8
WorkLoc                     32
ImpSyn                       5
CodeRev                      1
CodeRevHrs                2426
UnitTests                   29
PurchaseHow                196
PurchaseWhat                38
LanguageWorkedWith          11
LanguageDesireNextYear     134
DatabaseWorkedWith         453
DatabaseDesireNextYear    1042
PlatformWorkedWith         411
PlatformDesireNextYear     544
WebFrameWorkedWith        1393
WebFrameDesireNextYear    1617
MiscTechWorkedWith        2182
MiscTechDesireNextYear    1455
DevEnviron                  29
OpSys                       34
Containers                  82
BlockchainOrg             2322
BlockchainIs              2610
BetterLife                  98
ITperson                    35
OffOn                       38
SocialMedia                293
Extraversion                20
ScreenName                 507
SOVisit1st                 325
SOVisitFreq                  5
SOVisitTo                    1
SOFindAnswer                 3
SOTimeSaved                 50
SOHowMuchTime             1917
SOAccount                    1
SOPartFreq                1128
SOJobs                       6
EntTeams                     5
SOComm                       0
WelcomeChange               85
SONewContent              1965
Age                        287
Gender                      73
Trans                      123
Sexuality                  542
Ethnicity                  675
Dependents                 140
SurveyLength                19
SurveyEase                  14
dtype: int64

Find out how many rows are missing in the column 'WorkLoc'

In [13]:
df['WorkLoc'].isnull().sum()

32

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [14]:
# your code goes here
df["WorkLoc"].value_counts()

Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

<b>Quiz: What is the majority category under the column Employment?<b>

In [38]:
df["Employment"].value_counts().idxmax()

'Employed full-time'

<b>Quiz: Under the column " UndergradMajor", which category has the minimum number of rows?<b>

In [37]:
 df["UndergradMajor"].value_counts().idxmin()

'A health science (ex. nursing, pharmacy, radiology)'

Identify the value that is most frequent (majority) in the WorkLoc column.

In [ ]:
#make a note of the majority value here, for future reference
#Value most frequent = Office

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [15]:
df["WorkLoc"].fillna("office",inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [16]:
# your code goes here
df['WorkLoc'].isnull().sum()

0

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [39]:
# your code goes here
df["CompFreq"].value_counts().index

Index(['Yearly', 'Monthly', 'Weekly'], dtype='object')

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [18]:
import numpy as np

In [31]:
norm=[]
for row,value in zip(df['CompFreq'], df['CompTotal']):
        if row =='Monthly':
            norm.append(value*12)
        elif row=='Weekly':
            norm.append(value*52)
        else:
            norm.append(value)

            
df['NormalizedAnnualCompensation']=norm
df[['NormalizedAnnualCompensation']]

       NormalizedAnnualCompensation
0                           61000.0
1                          138000.0
2                           90000.0
3                          348000.0
4                           90000.0
...                             ...
11547                      130000.0
11548                       74400.0
11549                      105000.0
11550                       80000.0
11551                           NaN

[11398 rows x 1 columns]

In [33]:
df[["NormalizedAnnualCompensation"]].head(20)

    NormalizedAnnualCompensation
0                        61000.0
1                       138000.0
2                        90000.0
3                       348000.0
4                        90000.0
5                       114000.0
6                        36000.0
7                       103000.0
8                        69000.0
9                        96000.0
10                       84000.0
11                      114000.0
12                      104000.0
13                     1144000.0
14                     1152000.0
15                      156000.0
16                       18000.0
17                       76800.0
18                       60000.0
19                      400000.0

<b> Quiz: After removing the duplicate rows, how many respondents are being paid yearly?

In [47]:
df['CompFreq'].value_counts().Yearly

6073

<b> Quiz:What is the median NormalizedAnnualCompensation?

In [48]:
df["NormalizedAnnualCompensation"].median()

100000.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).